/**
 * Utility store for managing PDF Bookmarks, Text Highlights, and Study Notes
 * Saved in localStorage with sync helper functions.
 */

const BOOKMARKS_KEY_PREFIX = 'eduvault-pdf-bookmarks-';
const HIGHLIGHTS_KEY_PREFIX = 'eduvault-pdf-highlights-';

// ─── BOOKMARKS CRUD ──────────────────────────────────────────────────────────

export function getBookmarks(bookId) {
  if (!bookId) return [];
  try {
    const raw = localStorage.getItem(`${BOOKMARKS_KEY_PREFIX}${bookId}`);
    return raw ? JSON.parse(raw) : [];
  } catch (err) {
    console.error('Failed to get bookmarks:', err);
    return [];
  }
}

export function isPageBookmarked(bookId, chapterIdx, pageNum) {
  const list = getBookmarks(bookId);
  return list.some(
    (b) => b.chapterIdx === chapterIdx && b.pageNum === pageNum
  );
}

export function toggleBookmark(bookId, chapterIdx, pageNum, chapterName = '') {
  if (!bookId) return [];
  const list = getBookmarks(bookId);
  const existingIdx = list.findIndex(
    (b) => b.chapterIdx === chapterIdx && b.pageNum === pageNum
  );

  let updated;
  if (existingIdx >= 0) {
    updated = list.filter((_, idx) => idx !== existingIdx);
  } else {
    const newBookmark = {
      id: `bm_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
      chapterIdx,
      pageNum,
      chapterName,
      title: `Chapter: ${chapterName || 'General'} (Page ${pageNum})`,
      createdAt: new Date().toISOString(),
    };
    updated = [newBookmark, ...list];
  }

  try {
    localStorage.setItem(`${BOOKMARKS_KEY_PREFIX}${bookId}`, JSON.stringify(updated));
  } catch (err) {
    console.error('Failed to save bookmark:', err);
  }
  return updated;
}

// ─── HIGHLIGHTS & NOTES CRUD ──────────────────────────────────────────────────

export function getHighlights(bookId) {
  if (!bookId) return [];
  try {
    const raw = localStorage.getItem(`${HIGHLIGHTS_KEY_PREFIX}${bookId}`);
    return raw ? JSON.parse(raw) : [];
  } catch (err) {
    console.error('Failed to get highlights:', err);
    return [];
  }
}

export function addHighlight(bookId, { chapterIdx, pageNum, text, color = '#fef08a', note = '' }) {
  if (!bookId || (!text && !note)) return [];
  const list = getHighlights(bookId);

  const newHighlight = {
    id: `hl_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
    chapterIdx,
    pageNum,
    text: text ? text.trim() : '',
    color, // e.g. '#fef08a' (yellow), '#a7f3d0' (green), '#bae6fd' (blue), '#fbcfe8' (pink)
    note: note ? note.trim() : '',
    createdAt: new Date().toISOString(),
  };

  const updated = [newHighlight, ...list];
  try {
    localStorage.setItem(`${HIGHLIGHTS_KEY_PREFIX}${bookId}`, JSON.stringify(updated));
  } catch (err) {
    console.error('Failed to save highlight:', err);
  }
  return updated;
}

export function deleteHighlight(bookId, highlightId) {
  if (!bookId || !highlightId) return [];
  const list = getHighlights(bookId);
  const updated = list.filter((h) => h.id !== highlightId);
  try {
    localStorage.setItem(`${HIGHLIGHTS_KEY_PREFIX}${bookId}`, JSON.stringify(updated));
  } catch (err) {
    console.error('Failed to delete highlight:', err);
  }
  return updated;
}

export function updateHighlightNote(bookId, highlightId, newNote) {
  if (!bookId || !highlightId) return [];
  const list = getHighlights(bookId);
  const updated = list.map((h) => (h.id === highlightId ? { ...h, note: newNote.trim() } : h));
  try {
    localStorage.setItem(`${HIGHLIGHTS_KEY_PREFIX}${bookId}`, JSON.stringify(updated));
  } catch (err) {
    console.error('Failed to update highlight note:', err);
  }
  return updated;
}

// ─── MARKDOWN EXPORTER ────────────────────────────────────────────────────────

export function exportNotesAsMarkdown(bookTitle, bookmarks = [], highlights = []) {
  let md = `# 📖 Study Notes & Bookmarks: ${bookTitle}\n`;
  md += `*Generated by EduVault on ${new Date().toLocaleDateString()}*\n\n`;
  md += `---\n\n`;

  // Bookmarks section
  md += `## 🔖 Saved Page Bookmarks (${bookmarks.length})\n`;
  if (bookmarks.length === 0) {
    md += `*No bookmarks saved yet.*\n\n`;
  } else {
    bookmarks.forEach((bm, i) => {
      md += `${i + 1}. **Page ${bm.pageNum}** - ${bm.chapterName || 'Chapter'} *(Saved ${new Date(bm.createdAt).toLocaleDateString()})*\n`;
    });
    md += `\n`;
  }

  // Highlights & Notes section
  md += `## 🖍️ Highlights & Study Notes (${highlights.length})\n`;
  if (highlights.length === 0) {
    md += `*No highlights or notes saved yet.*\n\n`;
  } else {
    highlights.forEach((hl, i) => {
      md += `### ${i + 1}. Page ${hl.pageNum} ${hl.note ? `— *"${hl.note}"*` : ''}\n`;
      if (hl.text) {
        md += `> "${hl.text}"\n\n`;
      }
      if (hl.note) {
        md += `**Note:** ${hl.note}\n\n`;
      }
      md += `---\n`;
    });
  }

  // Trigger browser file download
  const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.setAttribute('download', `${bookTitle.replace(/[^a-z0-9]/gi, '_')}_EduVault_Notes.md`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  setTimeout(() => URL.revokeObjectURL(url), 4000);
}
